# Generated by Django 2.2.12 on 2020-05-11 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donate',
            new_name='Donations',
        ),
    ]
