# Generated by Django 2.2.12 on 2020-05-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_auto_20200511_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='first_name',
            field=models.CharField(default='TY', max_length=100),
        ),
        migrations.AddField(
            model_name='donations',
            name='last_name',
            field=models.CharField(default='TY', max_length=100),
        ),
    ]
