# Generated by Django 2.2.12 on 2020-05-11 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_books', models.IntegerField()),
                ('subject', models.CharField(choices=[('ENG', 'English'), ('MATH', 'Mathematics'), ('KISW', 'Kiswahili'), ('SST', 'Social Studies'), ('SCI', 'Science'), ('CRE', 'Christian Religious Studies'), ('ISSD', 'Islamic Studies'), ('HIS', 'History'), ('GRHY', 'Geography'), ('CHEM', 'Chemistry'), ('BIO', 'Biology'), ('PHY', 'Physics'), ('MSC', 'Music'), ('BSS', 'Business'), ('AGRI', 'Agriculture'), ('WWK', 'Wood-work'), ('DD', 'Drawing & Design'), ('AD', 'Art & Design'), ('TD', 'Technical Drawing'), ('PM', 'Power Mechanics'), ('COMP', 'Computer Studies'), ('SETB', 'Setbooks/Novels/Revision')], max_length=4)),
                ('school_grade', models.CharField(choices=[('BBC', ' Baby class'), ('GRD1', 'Grade 1'), ('GRD2', 'Grade 2'), ('GRD3', 'Grade 3'), ('GRD4', 'Grade 4'), ('GRD5', 'Grade 5'), ('GRD6', 'Grade 6'), ('GRD7', 'Grade 7'), ('GRD8', 'Grade 8'), ('GRD9', 'Grade 9'), ('GRD10', 'Grade 10'), ('GRD11', 'Grade 11'), ('GRD12', 'Grade 12'), ('GEN', 'General')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
